[tool.poetry]
name = "pyleague"
version = "0.1.0"
description = ""
authors = ["Fernando Miguel Hahne <fernandomhahne@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
python-frontmatter = "^1.0.1"
typer = "^0.9.0"
rich = "^13.3.4"

[tool.poetry.group.dev.dependencies]
black = "^23.12.0"
hypothesis = "^6.92.1"
isort = "^5.13.2"
mypy = "^1.2.0"
pylint = "^3"
pytest = "^7.3.1"
pytest-cov = "^4.0.0"

[tool.poetry.scripts]
pyleague = "pyleague.__main__:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88

[tool.pylint]
max-line-length = 88

[tool.pylint.messages_control]
disable = "E1136"
